apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: leosch1-leosch1-poi-map-app-dev
  annotations:
    argocd/app-name: leosch1-leosch1-poi-map-app-dev
    backstage.io/kubernetes-id: leosch1-leosch1-poi-map-app-dev
    backstage.io/kubernetes-namespace: leosch1
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=leosch1-leosch1-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/leosch1-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/leosch1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/leosch1/deployments/leosch1-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/leosch1-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://leosch1-poi-map-app-leosch1.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/leosch1"
  system: workshop-system-leosch1
  consumesApis:
    - gateway-api-leosch1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-leosch1
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/leosch1"
